#!/usr/bin/env sh
# Create and update a virtual environment

# Name the virtual environment "venv".
# Store its files in the ".venv" folder.
python3 -m venv .venv

# Upgrade pip (Python's package installer)
python3 -m pip install --upgrade pip

# Install everything in requirements.txt
python3 -m pip install -r requirements.txt

# Show installed packages
python3 -m pip list
