#!/usr/bin/env sh
# Create and update a virtual environment

# Use the same names as the textbook
python3 -m venv .venv

# Upgrade pip (Python's package installer)
python3 -m pip install --upgrade pip

# Install everything in requirements.txt
python3 -m pip install -r science/requirements.txt

# Show installed packages
python3 -m pip list
